font_family FiraCode Nerd Font Mono
font_size 14

map f11 toggle_fullscreen
map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard
map ctrl+t launch --cwd current --type tab
map ctrl+q close_window
map ctrl+w close_tab
